### ISSUE TITLE
А для совсем начинающих можно кратко как це собрать для чтения.

### ISSUE THREAD

**Issue by steelvan** [finom/seemple.js.org#15]
А для совсем начинающих можно краткую инструкцию как це собрать для чтения ?
Спасибо !

**Comment by finom** [comment]
Сімпл.жс це перейменований фреймворк matreshka.js. На хабрі є блог, там все
актуально, окрім імен https://m.habr.com/ru/company/matreshka/profile/

**Comment by steelvan** [comment]
Я це разумею, щчо симпл е нова версия матрешки.
Я инче  про друге пытаю.

Мне тяжело читать вашу справку из-за дюже великой килькости англицизмов.
Я хочу ее собрать на своем местном компьютере, исправить англицизмы на нормальные русские слова и спокойно читать.

Привет из Питера, пока Шария насмотришься на мове научишься размовлять :)

**Comment by steelvan** [comment]
У вас написано "Look at the NPM scripts for an info about how to build and how to run the website locally".
Я в npm плохо разбираюсь, но хочу собрать сайт местно.

**Comment by finom** [comment]
Нічого не можу зробити, пробачте :)

**Comment by steelvan** [comment]
Можно зробить краткую инструкцию в командах консоли, дякую.

**Comment by steelvan** [comment]
Ладно.

Выбрать "Все сразу", копивставка, правка, чтение, выгода.
Ага.
